#

FIND_PATH(PHYSX_INCLUDE_DIR PhysX/PxPhysicsAPI.h
      ${CMAKE_SOURCE_DIR}/include)

if(MSVC)
      FIND_LIBRARY(PHYSX_LIBRARY PhysX_64
            PATHS ${CMAKE_SOURCE_DIR}/lib)
      IF(PHYSX_INCLUDE_DIR AND PHYSX_LIBRARY)
      SET(PHYSX_FOUND TRUE)
      SET(PHYSX_LIBRARIES ${PHYSX_LIBRARY})
      ENDIF(PHYSX_INCLUDE_DIR AND PHYSX_LIBRARY)
endif()

IF(PHYSX_FOUND)
IF(NOT PHYSX_FIND_QUIETLY)
MESSAGE(STATUS "Found PHYSX: ${PHYSX_LIBRARIES}")
ENDIF(NOT PHYSX_FIND_QUIETLY)
ELSE(PHYSX_FOUND)
IF(PHYSX_FIND_REQUIRED)
MESSAGE(FATAL_ERROR "Could not find PHYSX")
ENDIF(PHYSX_FIND_REQUIRED)
ENDIF(PHYSX_FOUND)
